default['influxcsv']['user']  = 'influxcsv'
default['influxcsv']['group'] = 'influxcsv'
default['influxcsv']['deploy_dir'] = '/opt/influxcsv'
default['influxcsv']['home_dir']   = '/opt/influxcsv/current'
default['influxcsv']['virtualenv'] = '/opt/influxcsv/shared/env'
default['influxcsv']['git_url']      = 'https://github.com/jusbrasil/influxcsv.git'
default['influxcsv']['server_name']  = 'influxcsv.local'
